export const CONTACT_ADMIN_SUCCESS ='CONTACT_ADMIN_SUCCESS'
export const CONTACT_ADMIN_FAIL = 'CONTACT_ADMIN_SUCCESS'
export const CONTACT_ADMIN_RESET = 'CONTACT_ADMIN_SUCCESS'
export const CONTACT_ADMIN_REQUEST= 'CONTACT_ADMIN_SUCCESS'