export const CREATE_USER_SUCCESS ='CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
export const CREATE_USER_RESET = 'CREATE_USER_RESET'
export const CREATE_USER_REQUEST= 'CREATE_USER_REQUEST'



export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGIN_USER_RESET = 'LOGIN_USER_RESET'
export const LOGIN_USER_REQUEST= 'LOGIN_USER_REQUEST'